name: Daily tasks bot

on:
  push:
  schedule:
    - cron: '0 10 * * *'

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          GOOGLE_API_PW: ${{ secrets.GOOGLE_API_PW }}

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Use decrypted credentials
        run: |
          python main.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GG_ID: ${{ secrets.GG_ID }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
